### ISSUE TITLE
extc_stubs.c not msvc-firendly

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/ocamllibs#13]
This file has a problem with the joyous requirement of c to declare you variables at the top of the scope, specifically in get_real_path: sep,len,i,last  and later: data, handle.
Sorry about the lack of pull request.

**Comment by Gama11** [comment]
I also ran into this. Removing the `const` from `sep` seemed to fix the issue for me, but I'm not sure why.

@nadako Thoughts?

**Comment by nadako** [comment]
Eh. I don't know, I thought that kind of issues are forgotten since 90s. Should I move all var declarations to the top?

**Comment by Gama11** [comment]
I guess it's not being compiled with C99 (which shouldn't have any issues with this)?

**Comment by Gama11** [comment]
Seems that msvc only supports C89 and the other option is compiling as C++. Probably easiest to just move the declarations.

**Comment by Simn** [comment]
I agree.

**Comment by nadako** [comment]
#14
