### ISSUE TITLE
Troubles compiling extlib on Sabayon

### ISSUE THREAD

**Issue by skwerlman** [HaxeFoundation/ocamllibs#21]
First off, I suspect this may be either a distro-specific problem (based on issues I had getting ocaml itself working), or I'm just an idiot.

When running `make` for the haxe project, the build fails on `extLib.cxma` with:
```
File "bitSet.ml", line 37, characters 2-18:
Error: Unknown builtin primitive "%string_unsafe_set"
```

The full make log is here: https://gist.github.com/skwerlman/1ee9a09b2b91d1c424d3e9bf136e58f8#file-haxe_build_error-L16-L17

Did I miss a step somewhere?

ocaml version 4.05.0+dev0-2016-08-01
haxe version 3.3.0-rc1
gnu make 4.1

**Comment by ncannasse** [comment]
It's possible that %string_unsafe_set has been removed in 4.05 , maybe replace by %bytes_unsafe_set ?
Now if that's the code I wonder how we can support both versions with same codebase...

**Comment by Simn** [comment]
This is being addressed: https://github.com/ocaml/ocaml/pull/772

Not a problem on our end. Try using a stable version of OCaml for now.
